# Site settings
title: Austria
description: Austria may be a typical winter idyll, but the scene changes dramatically when the snow melts. What’s revealed is an irresistible summer landscape perfect for active breaks. Jutting, verdant mountains offer a wealth of trails snaking from one quaint Alpine village to another. National Parks are awash with resplendent, ancient trees and hidden, enchanting waterfalls. When the sun starts to sink, pick from award-winning dining or rustic local fare and look out over sublime scenery. Austria in summer is a breathtaking scene with a landscape full of drama, sunshine and fortuitous escapes.
baseurl: "/austria" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, bower_components, bower.json, README.md]
